// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: geekedu.proto

//微服务间通过 gRPC 通信

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用响应结构
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // 通用数据字段，后续可序列化JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_geekedu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_geekedu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_geekedu_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 用户注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // student/admin
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_geekedu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geekedu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_geekedu_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// 用户登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_geekedu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geekedu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_geekedu_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 登录响应（返回Token）
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_geekedu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geekedu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_geekedu_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 课程列表请求
type CourseListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseListRequest) Reset() {
	*x = CourseListRequest{}
	mi := &file_geekedu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseListRequest) ProtoMessage() {}

func (x *CourseListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geekedu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseListRequest.ProtoReflect.Descriptor instead.
func (*CourseListRequest) Descriptor() ([]byte, []int) {
	return file_geekedu_proto_rawDescGZIP(), []int{4}
}

// 发布课程请求
type CreateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"` // 字符串避免精度问题
	Intro         string                 `protobuf:"bytes,3,opt,name=intro,proto3" json:"intro,omitempty"`
	CoverFile     []byte                 `protobuf:"bytes,4,opt,name=cover_file,json=coverFile,proto3" json:"cover_file,omitempty"`  // 封面文件二进制
	CreatedBy     int64                  `protobuf:"varint,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"` // 创建者ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_geekedu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geekedu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_geekedu_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCourseRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *CreateCourseRequest) GetIntro() string {
	if x != nil {
		return x.Intro
	}
	return ""
}

func (x *CreateCourseRequest) GetCoverFile() []byte {
	if x != nil {
		return x.CoverFile
	}
	return nil
}

func (x *CreateCourseRequest) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

// 购买课程请求
type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_geekedu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geekedu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_geekedu_proto_rawDescGZIP(), []int{6}
}

func (x *CreateOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

// 获取播放链接请求
type GetPlayUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayUrlRequest) Reset() {
	*x = GetPlayUrlRequest{}
	mi := &file_geekedu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayUrlRequest) ProtoMessage() {}

func (x *GetPlayUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geekedu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayUrlRequest.ProtoReflect.Descriptor instead.
func (*GetPlayUrlRequest) Descriptor() ([]byte, []int) {
	return file_geekedu_proto_rawDescGZIP(), []int{7}
}

func (x *GetPlayUrlRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPlayUrlRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

// 获取播放链接响应
type GetPlayUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayUrl       string                 `protobuf:"bytes,1,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayUrlResponse) Reset() {
	*x = GetPlayUrlResponse{}
	mi := &file_geekedu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayUrlResponse) ProtoMessage() {}

func (x *GetPlayUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geekedu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayUrlResponse.ProtoReflect.Descriptor instead.
func (*GetPlayUrlResponse) Descriptor() ([]byte, []int) {
	return file_geekedu_proto_rawDescGZIP(), []int{8}
}

func (x *GetPlayUrlResponse) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

var File_geekedu_proto protoreflect.FileDescriptor

const file_geekedu_proto_rawDesc = "" +
	"\n" +
	"\rgeekedu.proto\x12\ageekedu\"D\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"]\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x13\n" +
	"\x11CourseListRequest\"\x95\x01\n" +
	"\x13CreateCourseRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x12\x14\n" +
	"\x05intro\x18\x03 \x01(\tR\x05intro\x12\x1d\n" +
	"\n" +
	"cover_file\x18\x04 \x01(\fR\tcoverFile\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\x03R\tcreatedBy\"J\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\"G\n" +
	"\x11GetPlayUrlRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\"/\n" +
	"\x12GetPlayUrlResponse\x12\x19\n" +
	"\bplay_url\x18\x01 \x01(\tR\aplayUrl2\xbb\x03\n" +
	"\x0eGeekEduService\x127\n" +
	"\bRegister\x12\x18.geekedu.RegisterRequest\x1a\x11.geekedu.Response\x121\n" +
	"\x05Login\x12\x15.geekedu.LoginRequest\x1a\x11.geekedu.Response\x12>\n" +
	"\rGetCourseList\x12\x1a.geekedu.CourseListRequest\x1a\x11.geekedu.Response\x12?\n" +
	"\fCreateCourse\x12\x1c.geekedu.CreateCourseRequest\x1a\x11.geekedu.Response\x12@\n" +
	"\vUploadVideo\x12\x1c.geekedu.CreateCourseRequest\x1a\x11.geekedu.Response(\x01\x12=\n" +
	"\vCreateOrder\x12\x1b.geekedu.CreateOrderRequest\x1a\x11.geekedu.Response\x12;\n" +
	"\n" +
	"GetPlayUrl\x12\x1a.geekedu.GetPlayUrlRequest\x1a\x11.geekedu.ResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_geekedu_proto_rawDescOnce sync.Once
	file_geekedu_proto_rawDescData []byte
)

func file_geekedu_proto_rawDescGZIP() []byte {
	file_geekedu_proto_rawDescOnce.Do(func() {
		file_geekedu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geekedu_proto_rawDesc), len(file_geekedu_proto_rawDesc)))
	})
	return file_geekedu_proto_rawDescData
}

var file_geekedu_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_geekedu_proto_goTypes = []any{
	(*Response)(nil),            // 0: geekedu.Response
	(*RegisterRequest)(nil),     // 1: geekedu.RegisterRequest
	(*LoginRequest)(nil),        // 2: geekedu.LoginRequest
	(*LoginResponse)(nil),       // 3: geekedu.LoginResponse
	(*CourseListRequest)(nil),   // 4: geekedu.CourseListRequest
	(*CreateCourseRequest)(nil), // 5: geekedu.CreateCourseRequest
	(*CreateOrderRequest)(nil),  // 6: geekedu.CreateOrderRequest
	(*GetPlayUrlRequest)(nil),   // 7: geekedu.GetPlayUrlRequest
	(*GetPlayUrlResponse)(nil),  // 8: geekedu.GetPlayUrlResponse
}
var file_geekedu_proto_depIdxs = []int32{
	1, // 0: geekedu.GeekEduService.Register:input_type -> geekedu.RegisterRequest
	2, // 1: geekedu.GeekEduService.Login:input_type -> geekedu.LoginRequest
	4, // 2: geekedu.GeekEduService.GetCourseList:input_type -> geekedu.CourseListRequest
	5, // 3: geekedu.GeekEduService.CreateCourse:input_type -> geekedu.CreateCourseRequest
	5, // 4: geekedu.GeekEduService.UploadVideo:input_type -> geekedu.CreateCourseRequest
	6, // 5: geekedu.GeekEduService.CreateOrder:input_type -> geekedu.CreateOrderRequest
	7, // 6: geekedu.GeekEduService.GetPlayUrl:input_type -> geekedu.GetPlayUrlRequest
	0, // 7: geekedu.GeekEduService.Register:output_type -> geekedu.Response
	0, // 8: geekedu.GeekEduService.Login:output_type -> geekedu.Response
	0, // 9: geekedu.GeekEduService.GetCourseList:output_type -> geekedu.Response
	0, // 10: geekedu.GeekEduService.CreateCourse:output_type -> geekedu.Response
	0, // 11: geekedu.GeekEduService.UploadVideo:output_type -> geekedu.Response
	0, // 12: geekedu.GeekEduService.CreateOrder:output_type -> geekedu.Response
	0, // 13: geekedu.GeekEduService.GetPlayUrl:output_type -> geekedu.Response
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_geekedu_proto_init() }
func file_geekedu_proto_init() {
	if File_geekedu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geekedu_proto_rawDesc), len(file_geekedu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geekedu_proto_goTypes,
		DependencyIndexes: file_geekedu_proto_depIdxs,
		MessageInfos:      file_geekedu_proto_msgTypes,
	}.Build()
	File_geekedu_proto = out.File
	file_geekedu_proto_goTypes = nil
	file_geekedu_proto_depIdxs = nil
}
