// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: geekedu.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeekEduService_Register_FullMethodName      = "/geekedu.GeekEduService/Register"
	GeekEduService_Login_FullMethodName         = "/geekedu.GeekEduService/Login"
	GeekEduService_GetCourseList_FullMethodName = "/geekedu.GeekEduService/GetCourseList"
	GeekEduService_CreateCourse_FullMethodName  = "/geekedu.GeekEduService/CreateCourse"
	GeekEduService_UploadVideo_FullMethodName   = "/geekedu.GeekEduService/UploadVideo"
	GeekEduService_CreateOrder_FullMethodName   = "/geekedu.GeekEduService/CreateOrder"
	GeekEduService_GetPlayUrl_FullMethodName    = "/geekedu.GeekEduService/GetPlayUrl"
)

// GeekEduServiceClient is the client API for GeekEduService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义gRPC服务
type GeekEduServiceClient interface {
	// 用户相关
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*Response, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Response, error)
	// 课程相关
	GetCourseList(ctx context.Context, in *CourseListRequest, opts ...grpc.CallOption) (*Response, error)
	CreateCourse(ctx context.Context, in *CreateCourseRequest, opts ...grpc.CallOption) (*Response, error)
	UploadVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateCourseRequest, Response], error)
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*Response, error)
	GetPlayUrl(ctx context.Context, in *GetPlayUrlRequest, opts ...grpc.CallOption) (*Response, error)
}

type geekEduServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeekEduServiceClient(cc grpc.ClientConnInterface) GeekEduServiceClient {
	return &geekEduServiceClient{cc}
}

func (c *geekEduServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, GeekEduService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geekEduServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, GeekEduService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geekEduServiceClient) GetCourseList(ctx context.Context, in *CourseListRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, GeekEduService_GetCourseList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geekEduServiceClient) CreateCourse(ctx context.Context, in *CreateCourseRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, GeekEduService_CreateCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geekEduServiceClient) UploadVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateCourseRequest, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GeekEduService_ServiceDesc.Streams[0], GeekEduService_UploadVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateCourseRequest, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GeekEduService_UploadVideoClient = grpc.ClientStreamingClient[CreateCourseRequest, Response]

func (c *geekEduServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, GeekEduService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geekEduServiceClient) GetPlayUrl(ctx context.Context, in *GetPlayUrlRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, GeekEduService_GetPlayUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeekEduServiceServer is the server API for GeekEduService service.
// All implementations must embed UnimplementedGeekEduServiceServer
// for forward compatibility.
//
// 定义gRPC服务
type GeekEduServiceServer interface {
	// 用户相关
	Register(context.Context, *RegisterRequest) (*Response, error)
	Login(context.Context, *LoginRequest) (*Response, error)
	// 课程相关
	GetCourseList(context.Context, *CourseListRequest) (*Response, error)
	CreateCourse(context.Context, *CreateCourseRequest) (*Response, error)
	UploadVideo(grpc.ClientStreamingServer[CreateCourseRequest, Response]) error
	CreateOrder(context.Context, *CreateOrderRequest) (*Response, error)
	GetPlayUrl(context.Context, *GetPlayUrlRequest) (*Response, error)
	mustEmbedUnimplementedGeekEduServiceServer()
}

// UnimplementedGeekEduServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeekEduServiceServer struct{}

func (UnimplementedGeekEduServiceServer) Register(context.Context, *RegisterRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedGeekEduServiceServer) Login(context.Context, *LoginRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGeekEduServiceServer) GetCourseList(context.Context, *CourseListRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCourseList not implemented")
}
func (UnimplementedGeekEduServiceServer) CreateCourse(context.Context, *CreateCourseRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCourse not implemented")
}
func (UnimplementedGeekEduServiceServer) UploadVideo(grpc.ClientStreamingServer[CreateCourseRequest, Response]) error {
	return status.Error(codes.Unimplemented, "method UploadVideo not implemented")
}
func (UnimplementedGeekEduServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedGeekEduServiceServer) GetPlayUrl(context.Context, *GetPlayUrlRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayUrl not implemented")
}
func (UnimplementedGeekEduServiceServer) mustEmbedUnimplementedGeekEduServiceServer() {}
func (UnimplementedGeekEduServiceServer) testEmbeddedByValue()                        {}

// UnsafeGeekEduServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeekEduServiceServer will
// result in compilation errors.
type UnsafeGeekEduServiceServer interface {
	mustEmbedUnimplementedGeekEduServiceServer()
}

func RegisterGeekEduServiceServer(s grpc.ServiceRegistrar, srv GeekEduServiceServer) {
	// If the following call panics, it indicates UnimplementedGeekEduServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeekEduService_ServiceDesc, srv)
}

func _GeekEduService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeekEduServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeekEduService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeekEduServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeekEduService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeekEduServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeekEduService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeekEduServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeekEduService_GetCourseList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeekEduServiceServer).GetCourseList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeekEduService_GetCourseList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeekEduServiceServer).GetCourseList(ctx, req.(*CourseListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeekEduService_CreateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeekEduServiceServer).CreateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeekEduService_CreateCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeekEduServiceServer).CreateCourse(ctx, req.(*CreateCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeekEduService_UploadVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GeekEduServiceServer).UploadVideo(&grpc.GenericServerStream[CreateCourseRequest, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GeekEduService_UploadVideoServer = grpc.ClientStreamingServer[CreateCourseRequest, Response]

func _GeekEduService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeekEduServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeekEduService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeekEduServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeekEduService_GetPlayUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeekEduServiceServer).GetPlayUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeekEduService_GetPlayUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeekEduServiceServer).GetPlayUrl(ctx, req.(*GetPlayUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeekEduService_ServiceDesc is the grpc.ServiceDesc for GeekEduService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeekEduService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geekedu.GeekEduService",
	HandlerType: (*GeekEduServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _GeekEduService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _GeekEduService_Login_Handler,
		},
		{
			MethodName: "GetCourseList",
			Handler:    _GeekEduService_GetCourseList_Handler,
		},
		{
			MethodName: "CreateCourse",
			Handler:    _GeekEduService_CreateCourse_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _GeekEduService_CreateOrder_Handler,
		},
		{
			MethodName: "GetPlayUrl",
			Handler:    _GeekEduService_GetPlayUrl_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadVideo",
			Handler:       _GeekEduService_UploadVideo_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "geekedu.proto",
}
